### ISSUE TITLE
# of classes

### ISSUE THREAD

**Issue by akinsevimli** [tudelft-iv/RTCnet#11]
Hello,

Why do you use number of classes as 2 in line 290?

Thank you.

**Comment by akinsevimli** [comment]
In addition, when we change it as 4, it gives error.

**Comment by andraspalffy** [comment]
Which file are you referring to?

**Comment by akinsevimli** [comment]
train_RTC_ensemble.py

> Which file are you referring to?

**Comment by akinsevimli** [comment]
> Which file are you referring to?

train_RTC_ensemble.py

**Comment by akinsevimli** [comment]
Which file are you referring to?

train_RTC_ensemble.py

**Comment by andraspalffy** [comment]
What is your error if you change it? @jiaaodong

**Comment by akinsevimli** [comment]
RuntimeError: weight tensor should be defined either for all 3 classes or no classes but got weight tensor of shape: [2] at /pytorch/aten/src/THCUNN/generic/ClassNLLCriterion.cu:44
