### ISSUE TITLE
of dataset

### ISSUE THREAD

**Issue by DaZhUUU** [tudelft-iv/RTCnet#12]
Hello, I want to ask why the labels and frame ids are random when gen_dataset.py generates the dataset? Are labels, frame ids and instance ids not related to the features? 
Thanks

**Comment by DaZhUUU** [comment]
And what do the low-level radar data means? It's the shape of the object? 
Thanks

**Comment by andraspalffy** [comment]
Hi, from the readme:
`Due to NDA issue, the dataset is not disclosed. The pseudo dataset can be generated by running:...`

We cannot share the real data as it is protected. Thus, we shared a way to generate fake data. That is where the random comes in.

Low-level radar data means the range-azimuth-doppler radar cube. Please check the paper.

**Comment by DaZhUUU** [comment]
I know low-level radar data means the radar cube. But why target-level data still means the range and azimuth estimation? Why is it more accurate? Is there any difference between two kind of data and how are they obtained?
Thanks

**Comment by andraspalffy** [comment]
Hello, please check the paper where target level data is defined too:

> Commercially available radars output a point-cloud of reflections called radar targets in every frame (sweep). Each radar target has the following features: range r and azimuth α, radar cross section RCS (i.e. reflectivity), and the object’s radial speed v r relative to the ego-vehicle.

Low level radar data is not more accurate but has more, unprocessed information. Target level data is already processed by expert knowledge, doing smart interpolations, etc.

**Comment by DaZhUUU** [comment]
You mean the information of the object target and the cluster target in the commercial radar? The object is target-level and the cluster is low-level.

**Comment by andraspalffy** [comment]
Hi, I think we mean different things.  Usually radars give you an object list (car, truck, pedestrian, etc.) or a point-cloud which you can process yourself. We do not use the first option at all, and call the second option target-level, as it is a point-cloud of targets.
**Another,** even lower level data is the radar-cube which we do use.

Please read the paper:

http://intelligent-vehicles.org/wp-content/uploads/2020/02/palffy2020ral_road_user_detection_radar_cube.pdf

Or check our video:

https://www.youtube.com/watch?v=7HxevlFwLdw&

**Comment by DaZhUUU** [comment]
So, can I get low-level data by mapping the target-level data into radar-cube? 

Thanks for your answering.

**Comment by andraspalffy** [comment]
If you have the radar cube, then yes, you can mimic what we did:
1, take target list
2, take radar cube
3, map targets to cube and crop a small neighbourhood around them

**Comment by DaZhUUU** [comment]
Sorry, it still confuses me. Your low-level data should be a 3D data, but it is a 2D data about samples and features when you generate it.

I can understand that the samples of target-level data like x, y, v, RCS, is about the number of target.

**Comment by andraspalffy** [comment]
Please be mire specific, what like gives you wrong dimensions and how you
check it.

**Comment by DaZhUUU** [comment]
In line 53 of gen_dataset.py, 

`features_low_level = 3000 * np.random.rand(num_samples, num_features - 4)`

It's a 2D data

**Comment by DaZhUUU** [comment]
Sorry, I used to study radar signal processing and just start learning CNN. So I can't know some details very well.

Thank you so much.

**Comment by andraspalffy** [comment]
Hey, good point, but in:

https://github.com/tudelft-iv/RTCnet/blob/f32a197eb0569c6fa98e2c98ed4e8e7f26fca8da/RTCnet/RTCnet.py#L314

we make it into a 3D image.

Basically, the data is stored in 1D and reshaped to be a cube when needed. Hope this helps.

**Comment by DaZhUUU** [comment]
OK. And if I can't get the radar cube from my radar, can I use a cube created by myself that the target-level data mapped in and the no data place is filled with zero?

Thanks

**Comment by andraspalffy** [comment]
Hi, in case you do not have the radar cube, I suggest using high-level mode
only, no need to make a "fake" all zero cube.

**Comment by DaZhUUU** [comment]
What's high-level mode? 

You mean the TargetMLP when `model_version == 3` in the line 288 of train_RTC_ensemble.py? Or something else?

Thanks

**Comment by DaZhUUU** [comment]
What's high-level mode?

You mean the TargetMLP when `model_version == 3` in the line 288 of train_RTC_ensemble.py? Or something else?

Thanks

**Comment by andraspalffy** [comment]
You do not need to send the same comment twice.
Yes exactly, see last commit and the comments in the code. version 3 is high level only.

**Comment by DaZhUUU** [comment]
OK, Thanks for your answering.
