### ISSUE TITLE
unable to execute last 2 commands 

### ISSUE THREAD

**Issue by siddupp** [tudelft-iv/RTCnet#14]
python3 test_RTC_ensemble.py
python3 test_RTC_ensemble.py

throwing  error as 
  File "instance_seg.py", line 340, in <module>
    config_list = os.listdir(result_DIR)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'F:\\VM\\IRP\\RTCnet-master\\results\\RTCtrain_info'

please help me to resolve this

**Comment by andraspalffy** [comment]
Dear sidddupp, this seems to me a simple path error, unrelated to our code.
Basically, you set a result_DIR path that does not exist. Please check if 'F:\VM\IRP\RTCnet-master\results\RTCtrain_info' is correct.

**Comment by siddupp** [comment]
Thank you for response
Sorry sir i am unable to understand what are you saying exactly, is there
any solutions to resolve this issue please suggest me.
        I am waiting for your reply

**Comment by andraspalffy** [comment]
Like I said, this is an issue on your side: you set a file path wrongly.  It literally says: "FileNotFoundError". File not found where it should be. Please check if 'F:\VM\IRP\RTCnet-master\results\RTCtrain_info' .

**Comment by siddupp** [comment]
Thank you sir  I will check.
