### ISSUE TITLE
unable to get the visual results even though executing the project successfully

### ISSUE THREAD

**Issue by siddupp** [tudelft-iv/RTCnet#15]
Hi sir,
I have successfully executed this project but i am unable to see the visual results as you shown in the gif's which you are attached can you pleases help me to obtain the visual results
![image](https://user-images.githubusercontent.com/59868895/190979068-5d191003-8514-4ae6-8ccf-9246af1f4cec.png)

**Comment by andraspalffy** [comment]
You will not see the gifs, because you do not have the radar- or camera data, caused by NDA reasons, as clearly said in the project.

**Comment by siddupp** [comment]
Ok thank you sir,
If i get dataset from the outside can i get visual results if yes how to do
that?

**Comment by andraspalffy** [comment]
You can get such results if you:
1, take the radar points
2, classify them one by one
3, overlay the points on camera image, and color by class.

Visualization was done in ROS, we do not share code for that.

**Comment by siddupp** [comment]
Ok, thanks.
