### ISSUE TITLE
Problems running instance_seg

### ISSUE THREAD

**Issue by lankerr** [tudelft-iv/RTCnet#17]
C:\Users\Lenovo\Desktop\REF\NET\1_CNN-cube\RTCnet\instance_seg.py:294: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  labels_pred_single[post_clst_id_single == id_of_cars_surrounded_by_a_lot_of_bikers] = 2
C:\Users\Lenovo\Desktop\REF\NET\1_CNN-cube\RTCnet\instance_seg.py:294: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  labels_pred_single[post_clst_id_single == id_of_cars_surrounded_by_a_lot_of_bikers] = 2
C:\Users\Lenovo\Desktop\REF\NET\1_CNN-cube\RTCnet\instance_seg.py:294: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  labels_pred_single[post_clst_id_single == id_of_cars_surrounded_by_a_lot_of_bikers] = 2

it repeats many times and at last it throws:

post_clustering: 100%|██████████| 200/200.0 [00:00<00:00, 1582.01it/s]
calculate precision and recall:   0%|          | 0/200.0 [00:00<?, ?it/s]C:\Users\Lenovo\Desktop\REF\NET\1_CNN-cube\RTCnet\instance_seg.py:70: RuntimeWarning: invalid value encountered in long_scalars
  if intersection/union >= 0.5:
C:\Users\Lenovo\Desktop\REF\NET\1_CNN-cube\RTCnet\instance_seg.py:84: RuntimeWarning: invalid value encountered in long_scalars
  if intersection/union >= 0.5:
C:\Users\Lenovo\Desktop\REF\NET\1_CNN-cube\RTCnet\instance_seg.py:153: RuntimeWarning: invalid value encountered in true_divide
  precision = num_TP_in_pred / num_instance_pred
C:\Users\Lenovo\Desktop\REF\NET\1_CNN-cube\RTCnet\instance_seg.py:154: RuntimeWarning: invalid value encountered in true_divide
  recall    = num_TP_in_true / num_instance_true
C:\Users\Lenovo\Desktop\REF\NET\1_CNN-cube\RTCnet\instance_seg.py:156: RuntimeWarning: invalid value encountered in true_divide
  return precision, recall, intersection_sum/union_sum, num_TP_single_target_total
calculate precision and recall: 100%|██████████| 200/200.0 [00:00<00:00, 4810.89it/s]
C:\Users\Lenovo\Desktop\REF\NET\1_CNN-cube\RTCnet\instance_seg.py:334: RuntimeWarning: invalid value encountered in true_divide
  return 2*precision*recall/(precision+recall)
precision_RTC [nan  0.  0. nan] recall_RTC [nan  0.  0.  0.]
number of TP object with 1 target: 0
f1 RTC:  [nan nan nan nan]
IoU RTC: [       nan 0.00150376 0.0015083  0.        ]

is the numpy too new or I don't use gpu?Ihave no idea

**Comment by andraspalffy** [comment]
Hello, this seems to me a division problem, which could come from the python version. Try printing out where the nan values are coming from.

**Comment by lankerr** [comment]
ok,it might be in instance_seg.py line 237:
 min_dist_mat = 10 * np.ones([int(post_clst_id_single.max() + 1), int(post_clst_id_single.max() + 1)])
and post_clst_id_single = [1,1,...,1,1]
but min_dist_mat = {ndarray:{0,0}}，but I think it is where the problem lies,but I'm not sure how to fix it;    :-(

**Comment by andraspalffy** [comment]
What data do you use? what is post_clst_id_single?

**Comment by lankerr** [comment]
I use the data by gen_dataset,I think I should read the article more carefully first,thank you for helping
