### ISSUE TITLE
Any code to visualize results? Kindly help

### ISSUE THREAD

**Issue by chowkamlee81** [tudelft-iv/RTCnet#6]
Any code to visualize results? Kindly help

**Comment by andraspalffy** [comment]
Hello, results were visualized in ROS, rviz.

**Comment by chowkamlee81** [comment]
Can u kindly provide rosbag and node so that people can get better on visualization results. Kindly help

**Comment by andraspalffy** [comment]
Hi, as mentioned in the review, we cannot share data because of our contract.
What are you trying to visualize exactly? Please be more precise.
We use the sphere list marker most of the time.

https://answers.ros.org/question/11135/plotting-a-markerarray-of-spheres-with-rviz/
