### ISSUE TITLE
Speed based thresholding

### ISSUE THREAD

**Issue by Gokulk1994** [tudelft-iv/RTCnet#7]
In [Targetloader.py](https://github.com/tudelft-iv/RTCnet/blob/master/RTCnet/TargetLoader.py), at line 126 and 156, the flag to check for features above the lower speed limit (only_fast) is not used. Instead, the only_slow flag is used twice (both for train and val). 

Is this a code error or during training and validation the lower speed(<speed_lower_lim) always needs to be masked when the only_slow flag is alone set to True? Also, this prevents the case to mask speeds<speed_lower_lim by setting the only_fast flag.

Example: lines 123-128

```
if only_slow:
    self.labels = self.labels[np.abs(self.features[:,2])<self.speed_upper_lim]
    self.features = self.features[np.abs(self.features[:,2])<self.speed_upper_lim,:]

if only_slow:
    self.labels = self.labels[np.abs(self.features[:,2])>self.speed_lower_lim]
    self.features = self.features[np.abs(self.features[:,2])>self.speed_lower_lim,:]
```

**Comment by andraspalffy** [comment]
Thanks for noticing, you are correct. See
 https://github.com/tudelft-iv/RTCnet/commit/2b1541f7d95f8f73e9ab2d9932a82b96ea8f727d
 
 btw we did not use these switches after some experiments.
