### ISSUE TITLE
Use only high dimension

### ISSUE THREAD

**Issue by akinsevimli** [tudelft-iv/RTCnet#8]
Hello,

I want to use high dimension only. However, I get this error.  I change feature_type='high'.

"RuntimeError: non-empty 4D or 5D (batch mode) tensor expected for input, but got ndim: 5"

How can I solve this problem?

Thank you.

**Comment by akinsevimli** [comment]
Anyone else there?

**Comment by andraspalffy** [comment]
Hello, please be more specific, what are you running exactly, what is your data, and which line gives you this error?

**Comment by akinsevimli** [comment]
Hello,
I want to work with only high-level features x,y,RCS, velocity not with low level features, because I have only high-level features.In your source code, there is a flag that makes the high level used. 
Line 247,262 , I change this line feature_type = 'low' to high gives this error

**Comment by andraspalffy** [comment]
But which line gives the actual error?

**Comment by akinsevimli** [comment]
I am posting full error page:

Traceback (most recent call last):
  File "/home/akin/Desktop/RTCnet/RTCnet/train_RTC_ensemble.py", line 539, in <module>
    main()
  File "/home/akin/Desktop/RTCnet/RTCnet/train_RTC_ensemble.py", line 362, in main
    chose_class=1
  File "/home/akin/Desktop/RTCnet/RTCnet/train_RTC_ensemble.py", line 98, in train_ova
    start_it=0
  File "/home/akin/Desktop/RTCnet/RTCnet/RTCnet_utils.py", line 172, in train
    val_init_loss = self._val_epoch(val_loader)
  File "/home/akin/Desktop/RTCnet/RTCnet/RTCnet_utils.py", line 113, in _val_epoch
    _, loss, res_dict = self._farward_pass(self.model, data)
  File "/home/akin/Desktop/RTCnet/RTCnet/RTCnet_utils.py", line 96, in _farward_pass
    preds = model(inputs)
  File "/home/akin/Desktop/RTCnet/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/akin/Desktop/RTCnet/RTCnet/RTCnet.py", line 261, in forward
    low_feat = self.conv_modules_para_2D[i](low_feat)
  File "/home/akin/Desktop/RTCnet/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/akin/Desktop/RTCnet/RTCnet/RTCnet.py", line 70, in forward
    features = self.max_pool(features)
  File "/home/akin/Desktop/RTCnet/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/akin/Desktop/RTCnet/venv/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 229, in forward
    self.return_indices)
  File "/home/akin/Desktop/RTCnet/venv/lib/python3.6/site-packages/torch/_jit_internal.py", line 267, in fn
    return if_false(*args, **kwargs)
  File "/home/akin/Desktop/RTCnet/venv/lib/python3.6/site-packages/torch/nn/functional.py", line 629, in _max_pool3d
    input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: non-empty 4D or 5D (batch mode) tensor expected for input, but got ndim: 5

**Comment by andraspalffy** [comment]
It seems like you pass on wrongly shaped (maybe empty) data and the maxpool has nothing to pool from.
Could you check the input you give to the network and the shape of each tensor you are passing to the pooling layers?

**Comment by akinsevimli** [comment]
Actually, I pass the data you give for example. Just created random data that you gave and run the train with high dimension.

**Comment by andraspalffy** [comment]
hello, @jiaaodong  was kind enough to make a hotfix for this.

**Comment by jiaaodong** [comment]
Hi @akinsevimli ,  thanks for the attention of this project. With high-level features dimension you could only use the fully connected layers, because the whole convolutional part is only used by low-level features. With high-level targets only, the model shall skip this part.
You shall set the model version in line 197 of TCnet/RTCnet/train_RTC_ensemble.py as 
`model_version   = 3`.
If you would use the fake dataset, you shall also set the number of features in the line 68 of RTCnet/gen_dataset.py to
`num_features = 4`.

This is a hot fix for your reference. The original intension of this project is still encouraging you to use the convolutional layers for low-level features.

**Comment by akinsevimli** [comment]
Hi @jiaaodong ,
Thank you for polite response. It was working until test_RTC_ensemble.py. I am getting this error:

  File "/snap/pycharm-community/238/plugins/python-ce/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-community/238/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/akin/Desktop/RTCnet/RTCnet/test_RTC_ensemble.py", line 381, in <module>
    main()
  File "/home/akin/Desktop/RTCnet/RTCnet/test_RTC_ensemble.py", line 248, in main
    use_gpu
  File "/home/akin/Desktop/RTCnet/RTCnet/test_RTC_ensemble.py", line 74, in test_ova
    model.load_state_dict(torch.load(model_path))
  File "/home/akin/Desktop/RTCnet/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for RTCnet:
	Missing key(s) in state_dict: "conv_modules_para_2D.0.conv_layer.weight", "conv_modules_para_2D.0.BN.weight", "conv_modules_para_2D.0.BN.bias", "conv_modules_para_2D.0.BN.running_mean", "conv_modules_para_2D.0.BN.running_var", "conv_modules_para_2D.1.conv_layer.weight", "conv_modules_para_2D.1.BN.weight", "conv_modules_para_2D.1.BN.bias", "conv_modules_para_2D.1.BN.running_mean", "conv_modules_para_2D.1.BN.running_var", "conv_modules_1D.0.conv_layer.weight", "conv_modules_1D.0.BN.weight", "conv_modules_1D.0.BN.bias", "conv_modules_1D.0.BN.running_mean", "conv_modules_1D.0.BN.running_var", "conv_modules_1D.1.conv_layer.weight", "conv_modules_1D.1.BN.weight", "conv_modules_1D.1.BN.bias", "conv_modules_1D.1.BN.running_mean", "conv_modules_1D.1.BN.running_var", "conv_modules_1D.2.conv_layer.weight", "conv_modules_1D.2.BN.weight", "conv_modules_1D.2.BN.bias", "conv_modules_1D.2.BN.running_mean", "conv_modules_1D.2.BN.running_var", "FCN_modules.0.weight", "FCN_modules.3.weight", "FCN_modules.6.weight". 
	Unexpected key(s) in state_dict: "FCN0.weight", "FCN0.bias", "FCN1.weight", "FCN1.bias", "FCN2.weight", "FCN2.bias".

**Comment by jiaaodong** [comment]
> Hi @jiaaodong ,
> Thank you for polite response. It was working until test_RTC_ensemble.py. I am getting this error:
> 
> File "/snap/pycharm-community/238/plugins/python-ce/helpers/pydev/pydevd.py", line 1483, in _exec
> pydev_imports.execfile(file, globals, locals) # execute the script
> File "/snap/pycharm-community/238/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
> exec(compile(contents+"\n", file, 'exec'), glob, loc)
> File "/home/akin/Desktop/RTCnet/RTCnet/test_RTC_ensemble.py", line 381, in
> main()
> File "/home/akin/Desktop/RTCnet/RTCnet/test_RTC_ensemble.py", line 248, in main
> use_gpu
> File "/home/akin/Desktop/RTCnet/RTCnet/test_RTC_ensemble.py", line 74, in test_ova
> model.load_state_dict(torch.load(model_path))
> File "/home/akin/Desktop/RTCnet/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
> self.**class**.**name**, "\n\t".join(error_msgs)))
> RuntimeError: Error(s) in loading state_dict for RTCnet:
> Missing key(s) in state_dict: "conv_modules_para_2D.0.conv_layer.weight", "conv_modules_para_2D.0.BN.weight", "conv_modules_para_2D.0.BN.bias", "conv_modules_para_2D.0.BN.running_mean", "conv_modules_para_2D.0.BN.running_var", "conv_modules_para_2D.1.conv_layer.weight", "conv_modules_para_2D.1.BN.weight", "conv_modules_para_2D.1.BN.bias", "conv_modules_para_2D.1.BN.running_mean", "conv_modules_para_2D.1.BN.running_var", "conv_modules_1D.0.conv_layer.weight", "conv_modules_1D.0.BN.weight", "conv_modules_1D.0.BN.bias", "conv_modules_1D.0.BN.running_mean", "conv_modules_1D.0.BN.running_var", "conv_modules_1D.1.conv_layer.weight", "conv_modules_1D.1.BN.weight", "conv_modules_1D.1.BN.bias", "conv_modules_1D.1.BN.running_mean", "conv_modules_1D.1.BN.running_var", "conv_modules_1D.2.conv_layer.weight", "conv_modules_1D.2.BN.weight", "conv_modules_1D.2.BN.bias", "conv_modules_1D.2.BN.running_mean", "conv_modules_1D.2.BN.running_var", "FCN_modules.0.weight", "FCN_modules.3.weight", "FCN_modules.6.weight".
> Unexpected key(s) in state_dict: "FCN0.weight", "FCN0.bias", "FCN1.weight", "FCN1.bias", "FCN2.weight", "FCN2.bias".

#10
